package main.memoire.app;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class MemoireFrame extends javax.swing.JFrame {
    private final List<Memoire> memoires;
    private final ListTableModel tableModel;
    
    public MemoireFrame() throws SQLException {
        initComponents();
        setSize(1000, 600);
        setLocationRelativeTo(null);
        
        // Initialize the memoires list (e.g., fetch from the database)
        memoires = MemoireConnection.getAllMemos();

        // Initialize the class-level tableModel
        tableModel = new ListTableModel(memoires);

        // Set the model for the JTable
        listTable.setModel(tableModel);

        // Make everything visible
        setVisible(true);
    }
    
    // Utility method to run database operations in background
    private void executeSwingWorker(SwingWorker<List<Memoire>, Void> worker) {
        worker.execute();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        sidebarPanel = new javax.swing.JPanel();
        sidebarHelpPanel = new javax.swing.JPanel();
        sidebarIcon = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        countLabel = new javax.swing.JLabel();
        todayMemoireBtn = new javax.swing.JButton();
        allMemoireBtn = new javax.swing.JButton();
        newMemoireBtn = new javax.swing.JButton();
        importBtn = new javax.swing.JButton();
        exportBtn = new javax.swing.JButton();
        separator2 = new javax.swing.JSeparator();
        separator1 = new javax.swing.JSeparator();
        mainPanel = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        searchBtn = new javax.swing.JButton();
        searchTxtField = new javax.swing.JTextField();
        listTableScrollPane = new javax.swing.JScrollPane();
        listTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MÉmoire");

        sidebarPanel.setBackground(new java.awt.Color(255, 241, 214));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(250, 600));
        sidebarPanel.setLayout(new java.awt.BorderLayout());

        sidebarHelpPanel.setOpaque(false);
        sidebarHelpPanel.setPreferredSize(new java.awt.Dimension(250, 340));
        sidebarHelpPanel.setLayout(new java.awt.GridBagLayout());

        sidebarIcon.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        sidebarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/thumbnail_bar.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        sidebarHelpPanel.add(sidebarIcon, gridBagConstraints);

        dateLabel.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        dateLabel.setText("Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        sidebarHelpPanel.add(dateLabel, gridBagConstraints);

        countLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        countLabel.setForeground(new java.awt.Color(165, 139, 108));
        countLabel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        sidebarHelpPanel.add(countLabel, gridBagConstraints);

        todayMemoireBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        todayMemoireBtn.setForeground(new java.awt.Color(165, 139, 108));
        todayMemoireBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/book_ribbon.png"))); // NOI18N
        todayMemoireBtn.setText("Mémoires of Today");
        todayMemoireBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        todayMemoireBtn.setBorderPainted(false);
        todayMemoireBtn.setFocusPainted(false);
        todayMemoireBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todayMemoireBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        sidebarHelpPanel.add(todayMemoireBtn, gridBagConstraints);

        allMemoireBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        allMemoireBtn.setForeground(new java.awt.Color(165, 139, 108));
        allMemoireBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/book_5.png"))); // NOI18N
        allMemoireBtn.setText("All Mémoires");
        allMemoireBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        allMemoireBtn.setBorderPainted(false);
        allMemoireBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allMemoireBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        sidebarHelpPanel.add(allMemoireBtn, gridBagConstraints);

        newMemoireBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        newMemoireBtn.setForeground(new java.awt.Color(165, 139, 108));
        newMemoireBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/note_add.png"))); // NOI18N
        newMemoireBtn.setText("New Mémoires");
        newMemoireBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        newMemoireBtn.setBorderPainted(false);
        newMemoireBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMemoireBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        sidebarHelpPanel.add(newMemoireBtn, gridBagConstraints);

        importBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        importBtn.setForeground(new java.awt.Color(165, 139, 108));
        importBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/upload.png"))); // NOI18N
        importBtn.setText("Import");
        importBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        importBtn.setBorderPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        sidebarHelpPanel.add(importBtn, gridBagConstraints);

        exportBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        exportBtn.setForeground(new java.awt.Color(165, 139, 108));
        exportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/download.png"))); // NOI18N
        exportBtn.setText("Export");
        exportBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        exportBtn.setBorderPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        sidebarHelpPanel.add(exportBtn, gridBagConstraints);

        separator2.setForeground(new java.awt.Color(176, 176, 176));
        separator2.setPreferredSize(new java.awt.Dimension(200, 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        sidebarHelpPanel.add(separator2, gridBagConstraints);

        separator1.setForeground(new java.awt.Color(176, 176, 176));
        separator1.setPreferredSize(new java.awt.Dimension(200, 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        sidebarHelpPanel.add(separator1, gridBagConstraints);

        sidebarPanel.add(sidebarHelpPanel, java.awt.BorderLayout.NORTH);

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.WEST);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(750, 600));
        mainPanel.setLayout(new java.awt.BorderLayout());

        searchPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchPanel.setAlignmentY(0.0F);
        searchPanel.setOpaque(false);
        searchPanel.setLayout(new javax.swing.BoxLayout(searchPanel, javax.swing.BoxLayout.X_AXIS));

        searchBtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/search.png"))); // NOI18N
        searchBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        searchBtn.setBorderPainted(false);
        searchPanel.add(searchBtn);

        searchTxtField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        searchTxtField.setText("Search Your Mémoires . . .");
        searchTxtField.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        searchPanel.add(searchTxtField);

        mainPanel.add(searchPanel, java.awt.BorderLayout.NORTH);

        listTable.setAutoCreateRowSorter(true);
        listTable.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        listTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Created", "Title", "Preview", "Category", "Last Updated"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTableMouseClicked(evt);
            }
        });
        listTableScrollPane.setViewportView(listTable);

        mainPanel.add(listTableScrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void todayMemoireBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todayMemoireBtnActionPerformed
        executeSwingWorker(new SwingWorker<List<Memoire>, Void>() {
            @Override
            protected List<Memoire> doInBackground() throws Exception {
                return MemoireConnection.getMemosCreatedToday();
            }

            @Override
            protected void done() {
                try {
                    List<Memoire> todayMemos = get();
                    updateTableData(todayMemos, "No mémoires for today.");
                } catch (InterruptedException | ExecutionException e) {
                    handleError("Error loading today's mémoires", e);
                }
            }
        });
    }//GEN-LAST:event_todayMemoireBtnActionPerformed

    private void allMemoireBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allMemoireBtnActionPerformed
        executeSwingWorker(new SwingWorker<List<Memoire>, Void>() {
            @Override
            protected List<Memoire> doInBackground() throws Exception {
                return MemoireConnection.getAllMemos();
            }

            @Override
            protected void done() {
                try {
                    List<Memoire> allMemos = get();
                    updateTableData(allMemos, "You don't have any mémoires.");
                } catch (InterruptedException | ExecutionException e) {
                    handleError("Error loading all mémoires", e);
                }
            }
        });
    }//GEN-LAST:event_allMemoireBtnActionPerformed

    private void newMemoireBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMemoireBtnActionPerformed
        // Create a new Memoire object with default values
        WritingFrame writingFrame = new WritingFrame();
        writingFrame.setVisible(true);
    }//GEN-LAST:event_newMemoireBtnActionPerformed

    private void listTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTableMouseClicked
        int selectedRow = listTable.getSelectedRow();
        if (selectedRow != -1) {
            Memoire selectedMemoire = memoires.get(selectedRow);
            WritingFrame writingFrame = new WritingFrame();
            writingFrame.setMemoireData(selectedMemoire);
            writingFrame.setVisible(true);
        }
    }//GEN-LAST:event_listTableMouseClicked
    
    // Update table data or show a message if no data is found
    private void updateTableData(List<Memoire> data, String noDataMessage) {
        if (data.isEmpty()) {
            JOptionPane.showMessageDialog(this, noDataMessage);
        } else {
            tableModel.refreshData(data);
            refreshTable();
        }
    }
    
    // Handle errors uniformly
    private void handleError(String message, Exception e) {
        JOptionPane.showMessageDialog(this, message + ": " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        Logger.getLogger(MemoireFrame.class.getName()).log(Level.SEVERE, message, e);
    }

    private void refreshTable() {
        listTable.revalidate();
        listTable.repaint();
    }
    
    // Inner TableModel class
    private static class ListTableModel extends AbstractTableModel {
        private final List<Memoire> memoires;
        private final String[] columnNames = {"Day & Date Created", "Title", "Preview", "Category", "Last Edited"};
        private final SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, dd-MM-yyyy");
        private final SimpleDateFormat timestampFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");

        public ListTableModel(List<Memoire> memoires) {
            this.memoires = new CopyOnWriteArrayList<>(memoires);
        }

        @Override
        public int getRowCount() {
            return memoires.size();
        }

        @Override
        public int getColumnCount() {
            return columnNames.length;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Memoire memoire = memoires.get(rowIndex);
            if (memoire == null) return null;

            return switch (columnIndex) {
                case 0 -> formatDate(memoire.getDayDateCreated());
                case 1 -> memoire.getTitle() != null ? memoire.getTitle() : "";
                case 2 -> getPreview(memoire.getContents());
                case 3 -> memoire.getCategory() != null ? memoire.getCategory() : "";
                case 4 -> formatTimestamp(memoire.getLastEdited());
                default -> null;
            };
        }

        @Override
        public String getColumnName(int column) {
            return columnNames[column];
        }

        private String formatDate(java.sql.Date date) {
            return date != null ? dateFormat.format(date) : "";
        }

        private String formatTimestamp(java.sql.Timestamp timestamp) {
            return timestamp != null ? timestampFormat.format(timestamp) : "";
        }

        private String getPreview(String contents) {
            return (contents != null && contents.length() > 20) ? contents.substring(0, 20) + "..." : (contents != null ? contents : "");
        }

        public void refreshData(List<Memoire> updatedMemoires) {
            memoires.clear();
            memoires.addAll(updatedMemoires);
            fireTableDataChanged();
        }
    }
    
    //Don't delete this
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemoireFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemoireFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemoireFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemoireFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new MemoireFrame().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(MemoireFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allMemoireBtn;
    private javax.swing.JLabel countLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton exportBtn;
    private javax.swing.JButton importBtn;
    private javax.swing.JTable listTable;
    private javax.swing.JScrollPane listTableScrollPane;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton newMemoireBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JPanel sidebarHelpPanel;
    private javax.swing.JLabel sidebarIcon;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JButton todayMemoireBtn;
    // End of variables declaration//GEN-END:variables
}
